<?php

namespace Database\Seeders;

use App\Models\Raza;
use Illuminate\Database\Seeder;

class RazaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        function insertarConArray($type, $array_razas)
        {
            for ($item = 0; $item < count($array_razas); $item++) {
                foreach ($array_razas as $raza) {
                    $raza = new Raza;
                    $raza->pettype_id = $type;
                    $raza->name = $array_razas[$item];
                    $raza->save();
                    $item += 1;
                }
            }
        }

        $caninos = [
            'Affenpinscher',
            'Airedale Terrier',
            'Akita Americano',
            'Akita Inu',
            'Alaskan Malamute',
            'American Staffordshire Terrier',
            'Antiguo perro de muestra danés',
            'Azawakh',
            'Azul de Gascuña',
            'Basenji',
            'Basset artesiano de Normandía',
            'Basset de los Alpes',
            'Basset Hound',
            'Basset leonado de Bretaña',
            'Beagle',
            'Beagle-Harrier',
            'Beauceron',
            'Bedlington Terrier',
            'Bergamasco',
            'Bichón boloñés',
            'Bichón frisé',
            'Bichón Habanero',
            'Bichón maltés',
            'Billy',
            'Black and Tan Coonhound',
            'Bobtail',
            'Boerboel',
            'Border collie',
            'Border Terrier',
            'Borzoi',
            'Boston terrier',
            'Bóxer',
            'Boyero de Appenzell',
            'Boyero de Berna',
            'Boyero de Entlebuch',
            'Boyero de Flandes',
            'Boyero de las Ardenas',
            'Braco alemán',
            'Braco alemán de pelo corto',
            'Braco Alemán de Pelo Duro',
            'Braco austriaco negro y fuego',
            'Braco de Ariège',
            'Braco de Auvernia',
            'Braco de Borbón',
            'Braco de Weimar',
            'Braco eslovaco de pelo duro',
            'Braco francés',
            'Braco húngaro',
            'Braco Italiano',
            'Braco Saint-Germain',
            'Briquet grifón vendeano',
            'Broholmer',
            'Buhund noruego',
            'Bull Terrier',
            'Bulldog Americano',
            'Bulldog francés',
            'Bulldog inglés',
            'Bullmastiff',
            'Cairn Terrier',
            'Cane Corso',
            'Caniche',
            'Cavalier King Charles Spaniel',
            'Cazador de alces noruego',
            'Chihuahua',
            'Chow Chow',
            'Cirneco del Etna',
            'Clumber Spaniel',
            'Cobrador de pelo liso',
            'Cobrador de pelo rizado',
            'Cocker Spaniel americano',
            'Cocker Spaniel inglés',
            'Collie barbudo',
            'Collie de pelo corto',
            'Collie de pelo largo',
            'Corgi galés de Pembroke',
            'Cotón de Tulear',
            'Crestado chino',
            'Crestado rodesiano',
            'Cursinu',
            'Dálmata',
            'Dandie Dinmont',
            'Dóberman',
            'Dogo argentino',
            'Dogo de Burdeos',
            'Dogo del Tíbet',
            'Dogo mallorquín',
            'Drever',
            'Eurasier',
            'Field Spaniel',
            'Fila Brasileiro',
            'Fila de San Miguel',
            'Fox Terrier',
            'Foxhound americano',
            'Foxhound inglés',
            'Galgo afgano',
            'Galgo español',
            'Galgo inglés',
            'Galgo italiano',
            'Galgo polaco',
            'Gascon saintongeois',
            'Golden Retriever',
            'Gordon Setter',
            'Gran basset grifón vendeano',
            'Gran boyero suizo',
            'Gran danés',
            'Gran grifón vendeano',
            'Gran Munsterlander',
            'Gran sabueso anglo-francés blanco y naranja',
            'Gran sabueso anglo-francés blanco y negro',
            'Gran sabueso anglo-francés tricolor',
            'Grifón de Bruselas',
            'Grifón de muestra bohemio de pelo duro',
            'Grifón de muestra de pelo duro',
            'Grifón leonado de Bretaña',
            'Grifón Nivernais',
            'Harrier',
            'Hokkaido',
            'Hovawart',
            'Husky siberiano',
            'Jack Russell Terrier',
            'Jämthund',
            'Kai',
            'Kelpie australiano',
            'Kerry Blue Terrier',
            'King Charles Spaniel',
            'Kishu',
            'Komondor',
            'Kromfohrländer',
            'Kuvasz',
            'Labrador Retriever',
            'Lagotto Romagnolo',
            'Laika de Siberia occidental',
            'Laika de Siberia oriental',
            'Laika ruso europeo',
            'Lakeland Terrier',
            'Landseer',
            'Lebrel escocés',
            'Lebrel húngaro',
            'Lebrel irlandés',
            'Leonberger',
            'Lhasa Apso',
            'Lundehund',
            'Manchester Terrier',
            'Mastín del Pirineo',
            'Mastín español',
            'Mastín inglés',
            'Mastín napolitano',
            'Mudi',
            'Münsterländer pequeño',
            'Otterhound',
            'Papillón',
            'Parson Russell Terrier',
            'Pastor alemán',
            'Pastor belga',
            'Pastor Blanco Suizo',
            'Pastor de Anatolia',
            'Pastor de Bosnia-Herzegovina y Croacia',
            'Pastor de Brie',
            'Pastor de Karst',
            'Pastor de las islas Shetland',
            'Pastor de los Pirineos',
            'Pastor de Maremma',
            'Pastor de Picardía',
            'Pastor de Tatra',
            'Pastor del Cáucaso',
            'Pastor eslovaco',
            'Pastor finlandés de Laponia',
            'Pastor ganadero australiano',
            'Pastor holandés',
            'Pastor islandés',
            'Pastor lapón de Suecia',
            'Pastor mallorquín',
            'Pastor ovejero australiano',
            'Pastor polaco de las llanuras',
            'Pastor rumano de Mioritza',
            'Pastor ucraniano',
            'Pastor Yugoslavo',
            'Pekinés',
            'Pequeño Basset Grifón vendeano',
            'Pequeño Brabantino',
            'Pequeño perro león',
            'Pequeño perro ruso',
            'Pequeño sabueso de Suiza',
            'Perdiguero alemán',
            'Perdiguero de Burgos',
            'Perdiguero de Drente',
            'Perdiguero frisón',
            'Perdiguero portugués',
            'Perro de agua americano',
            'Perro de agua español',
            'Perro de agua francés',
            'Perro de agua frisón',
            'Perro de agua irlandés',
            'Perro de agua portugués',
            'Perro de Canaán',
            'Perro de Castro Laboreiro',
            'Perro de caza polaco',
            'Perro de Chindo',
            'Perro de Groenlandia',
            'Perro de la Sierra de la Estrela',
            'Perro de montaña de Formosa',
            'Perro de montaña de los Pirineos',
            'Perro de Montaña del Atlas',
            'Perro de muestra alemán de pelo cerdoso',
            'Perro de muestra alemán de pelo duro',
            'Perro de osos de Carelia',
            'Perro de San Huberto',
            'Perro esquimal canadiense',
            'Perro Finlandés de Laponia',
            'Perro lobo checoslovaco',
            'Perro lobo de Saarloos',
            'Perro pastor catalán',
            'Perro pastor croata',
            'Perro pastor de Asia central',
            'Perro pastor portugués',
            'Perro sin pelo del Perú',
            'Perro tejonero de Westfalia',
            'Pharaoh Hound',
            'Pinscher',
            'Pinscher austríaco',
            'Podenco canario',
            'Podenco ibicenco',
            'Podenco portugués',
            'Pointer inglés',
            'Poitevino',
            'Pomerania',
            'Porcelana',
            'Presa Canario',
            'Pudelpointer',
            'Pug',
            'Puli',
            'Pumi',
            'Rafeiro do Alentejo',
            'Ratonero holandés',
            'Retriever de Chesapeake',
            'Retriever de Nueva Escocia',
            'Ridgeback tailandés',
            'Rottweiler',
            'Sabueso anglo-francés de tamaño mediano',
            'Sabueso artesiano',
            'Sabueso bávaro de montaña',
            'Sabueso de Bosnia de pelo cerdoso',
            'Sabueso de Hamilton',
            'Sabueso de Hannover',
            'Sabueso de Hygen',
            'Sabueso de Istria de pelo corto',
            'Sabueso de Istria de pelo duro',
            'Sabueso de montaña de Montenegro',
            'Sabueso de Schiller',
            'Sabueso de Småland',
            'Sabueso del Ariège',
            'Sabueso del Tirol',
            'Sabueso del Valle de Save',
            'Sabueso eslovaco',
            'Sabueso español',
            'Sabueso estirio de pelo áspero',
            'Sabueso finlandés',
            'Sabueso francés blanco y naranja',
            'Sabueso francés blanco y negro',
            'Sabueso francés tricolor',
            'Sabueso Halden',
            'Sabueso helénico',
            'Sabueso italiano',
            'Sabueso noruego',
            'Sabueso polaco',
            'Sabueso serbio',
            'Sabueso suizo',
            'Sabueso tricolor serbio',
            'Saluki',
            'Samoyedo',
            'San Bernardo',
            'Schapendoes neerlandés',
            'Schipperke',
            'Schnauzer',
            'Sealyham terrier',
            'Setter inglés',
            'Setter irlandés',
            'Setter irlandés rojo y blanco',
            'Shar Pei',
            'Shiba Inu',
            'Shih Tzu',
            'Shikoku Inu',
            'Skye Terrier',
            'Sloughi',
            'Spaniel azul de Picardía',
            'Spaniel bretón',
            'Spaniel de Pont-Audemer',
            'Spaniel francés',
            'Spaniel holandés',
            'Spaniel japonés',
            'Spaniel picardo',
            'Spaniel tibetano',
            'Spinone italiano',
            'Spitz de Norrbotten',
            'Spitz finlandés',
            'Spitz japonés',
            'Springer spaniel galés',
            'Springer Spaniel inglés',
            'Staffordshire bull terrier',
            'Sussex Spaniel',
            'Teckel',
            'Terranova',
            'Terrier alemán',
            'Terrier australiano',
            'Terrier brasileño',
            'Terrier checo',
            'Terrier de Norfolk y Terrier de Norwich',
            'Terrier escocés',
            'Terrier galés',
            'Terrier Glen de Imaal irlandés',
            'Terrier inglés miniatura',
            'Terrier irlandés',
            'Terrier irlandés de pelo suave',
            'Terrier japonés',
            'Terrier ruso negro',
            'Terrier tibetano',
            'Tosa Inu',
            'Vallhund sueco',
            'Vizsla',
            'Volpino italiano',
            'Westie',
            'Whippet',
            'Xoloitzcuintle',
            'Yorkshire Terrier'
        ];
        $felinos = [
            'Abisinio',
            'American Shorthair',
            'American Wirehair',
            'Angora turco',
            'Azul ruso',
            'Balinés',
            'Bengala',
            'Birmano',
            'Bobtail Americano',
            'Bobtail japonés',
            'Bombay',
            'Bosque de Noruega',
            'British Longhair',
            'British Shorthair',
            'Burmilla',
            'California Spangled',
            'Californian Rex',
            'Cartujo',
            'Ceilán',
            'Chausie',
            'Cornish Rex',
            'Curl americano',
            'Cymric',
            'Devon Rex',
            'Don Sphynx',
            'Exótico',
            'Gato común',
            'Gato común europeo',
            'Gato esfinge',
            'Gato Siberiano',
            'Gato Van turco',
            'German Rex',
            'Habana Brown',
            'Highland Fold y Highland Straight',
            'Himalayo',
            'Javanés',
            'Khao Manee',
            'Korat',
            'LaPerm',
            'Maine Coon',
            'Manx',
            'Mau egipcio',
            'Munchkin',
            'Nebelung',
            'Ocicat',
            'Oriental',
            'Persa',
            'Persa Chinchilla',
            'Peterbald',
            'Pixie Bob',
            'Ragamuffin',
            'Ragdoll',
            'Safari',
            'Sagrado de Birmania',
            'Savannah',
            'Scottish Fold',
            'Selkirk Rex',
            'Siamés',
            'Siamés thai',
            'Singapura',
            'Snowshoe',
            'Sokoke',
            'Somalí',
            'Tiffany',
            'Tonkinés',
            'Toyger',
            'York Chocolate'
        ];

        $aves = [
            'Cotorro',
            'Agapornis',
            'Agapornis roseicollis',
            'Cacatúa',
            'Canario',
            'Diamante de gould',
            'Diamante mandarín',
            'Loro yaco',
            'Ninfa',
            'Periquito de Bourke',
            'Periquito',
            'Pinzones'
        ];

        $peces = [
            'Pez ángel',
            'Pez betta',
            'Pez guppy',
            'Pez disco',
            'Pez tetra neón',
            'Pez dorado',
            'Pez gurami enano',
            'Pez platy',
            'Pez ramirezi',
            'Pez cíclido convicto'
        ];

        $reptiles = [];


        insertarConArray(1, $caninos);

        insertarConArray(2, $felinos);

        insertarConArray(3, $aves);

        insertarConArray(4, $peces);

        // insertarConArray(5, $reptiles);



    }
}
